export const MOCK_COURSES = [
  {
    _id: '658c1f107f9c8f0012345601',
    title: 'The Complete React & Next.js Masterclass',
    subtitle: 'Build production-ready apps with React 19, Next.js 15, and modern tooling',
    description: 'Master React from the ground up. This comprehensive course covers everything from React fundamentals to advanced patterns like Server Components, Suspense, and the App Router in Next.js 15. You will build 5 real-world projects including an e-commerce platform, a social media dashboard, and a real-time chat application. Perfect for developers who want to level up their frontend skills with the most in-demand JavaScript framework.',
    price: 14.99,
    originalPrice: 89.99,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
    instructor: {
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
      title: 'Senior Frontend Engineer at Meta',
      bio: '10+ years building web applications. Previously at Google and Stripe.',
    },
    category: 'Web Development',
    level: 'Intermediate',
    rating: 4.8,
    totalRatings: 12847,
    studentsEnrolled: 67432,
    totalDuration: '42h 30m',
    totalLessons: 284,
    tags: ['React', 'Next.js', 'JavaScript', 'Frontend', 'Web Dev'],
    isBestseller: true,
    lessons: [
      { title: 'Welcome & Course Overview', duration: '5:20', isPreview: true },
      { title: 'Setting Up Your Development Environment', duration: '12:45', isPreview: true },
      { title: 'JSX Deep Dive — How React Renders UI', duration: '18:30', isPreview: false },
      { title: 'State Management with useState & useReducer', duration: '22:15', isPreview: false },
    ],
    reviews: [
      { userName: 'Alex Rivera', rating: 5, comment: 'Best React course I have ever taken. Sarah explains complex concepts so clearly.' },
      { userName: 'Priya Sharma', rating: 5, comment: 'The Next.js section is gold. Built my portfolio site using what I learned here.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345602',
    title: 'Python for Data Science & Machine Learning Bootcamp',
    subtitle: 'Learn Python, Pandas, NumPy, Scikit-Learn, TensorFlow and build ML models',
    description: 'Go from Python beginner to Data Science professional. This bootcamp covers Python programming, data analysis with Pandas and NumPy, data visualization with Matplotlib and Seaborn, machine learning with Scikit-Learn, and deep learning with TensorFlow. Includes 20+ hands-on projects with real datasets from Kaggle competitions.',
    price: 16.99,
    originalPrice: 94.99,
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    instructor: {
      name: 'Dr. James Okonkwo',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
      title: 'Lead Data Scientist at Netflix',
      bio: 'PhD in Machine Learning from Stanford. 8 years in data science.',
    },
    category: 'Data Science',
    level: 'Beginner',
    rating: 4.7,
    totalRatings: 18234,
    studentsEnrolled: 89120,
    totalDuration: '52h 15m',
    totalLessons: 342,
    tags: ['Python', 'Data Science', 'Machine Learning', 'TensorFlow', 'Pandas'],
    isBestseller: true,
    lessons: [
      { title: 'Python Fundamentals Crash Course', duration: '25:00', isPreview: true },
      { title: 'NumPy — The Foundation of Data Science', duration: '30:15', isPreview: true },
    ],
    reviews: [
      { userName: 'Emily Zhang', rating: 5, comment: 'Went from zero Python to landing a data analyst role in 4 months!' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345603',
    title: 'iOS & SwiftUI — Build 20 Real-World Apps',
    subtitle: 'Master Swift, SwiftUI, Core Data, CloudKit, and App Store deployment',
    description: 'Learn iOS development by building 20 complete apps from scratch. Covers SwiftUI, UIKit interop, Core Data persistence, CloudKit sync, push notifications, in-app purchases, and App Store submission. Each project teaches new concepts while reinforcing fundamentals.',
    price: 19.99,
    originalPrice: 109.99,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    instructor: {
      name: 'Anika Patel',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
      title: 'iOS Lead at Airbnb',
      bio: 'Published 12 apps on the App Store. Apple WWDC scholar.',
    },
    category: 'Mobile Development',
    level: 'Intermediate',
    rating: 4.9,
    totalRatings: 8456,
    studentsEnrolled: 34521,
    totalDuration: '48h 45m',
    totalLessons: 310,
    tags: ['iOS', 'Swift', 'SwiftUI', 'Mobile', 'Apple'],
    isBestseller: true,
    lessons: [
      { title: 'Swift Language Essentials', duration: '20:00', isPreview: true },
      { title: 'Your First SwiftUI App', duration: '15:30', isPreview: true },
    ],
    reviews: [
      { userName: 'David Kim', rating: 5, comment: 'Anika is an incredible teacher. My app got featured on the App Store!' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345604',
    title: 'Generative AI & LLM Engineering with Python',
    subtitle: 'Build AI apps with OpenAI, LangChain, RAG, fine-tuning, and vector databases',
    description: 'The definitive course on building production AI applications. Learn to work with large language models, build RAG pipelines with vector databases, fine-tune models, create AI agents with LangChain, and deploy scalable AI services. Covers prompt engineering, embeddings, Pinecone, ChromaDB, and real-world AI product development.',
    price: 24.99,
    originalPrice: 149.99,
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
    instructor: {
      name: 'Dr. Michael Torres',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
      title: 'AI Research Lead at OpenAI',
      bio: 'Former Google DeepMind researcher. Published 30+ papers on NLP.',
    },
    category: 'AI & Machine Learning',
    level: 'Advanced',
    rating: 4.9,
    totalRatings: 6234,
    studentsEnrolled: 28940,
    totalDuration: '38h 20m',
    totalLessons: 198,
    tags: ['AI', 'LLM', 'ChatGPT', 'LangChain', 'Python', 'RAG'],
    isBestseller: true,
    lessons: [
      { title: 'The LLM Revolution — Understanding GPT', duration: '18:00', isPreview: true },
      { title: 'OpenAI API — Your First AI App', duration: '22:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Nina Kowalski', rating: 5, comment: 'This course helped me build an AI startup. Absolutely transformative.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345605',
    title: 'AWS Solutions Architect — Complete Guide',
    subtitle: 'Pass the AWS SAA-C03 exam and master cloud architecture',
    description: 'Become an AWS Solutions Architect. This course covers all AWS services needed for the SAA-C03 certification: EC2, S3, RDS, Lambda, CloudFormation, VPC, IAM, and more. Includes hands-on labs, architecture diagrams, practice exams, and real-world case studies from enterprise deployments.',
    price: 12.99,
    originalPrice: 79.99,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    instructor: {
      name: 'Lisa Nakamura',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&q=80',
      title: 'Principal Cloud Architect at AWS',
      bio: 'All 12 AWS certifications. Architected systems serving 100M+ users.',
    },
    category: 'Cloud Computing',
    level: 'Intermediate',
    rating: 4.7,
    totalRatings: 15678,
    studentsEnrolled: 72345,
    totalDuration: '44h 10m',
    totalLessons: 356,
    tags: ['AWS', 'Cloud', 'DevOps', 'Architecture', 'Certification'],
    isBestseller: true,
    lessons: [
      { title: 'Cloud Computing Fundamentals', duration: '15:00', isPreview: true },
      { title: 'IAM — Identity & Access Management', duration: '28:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Tom Bradley', rating: 5, comment: 'Passed my SAA-C03 on the first try with a score of 891/1000!' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345606',
    title: 'UI/UX Design — From Figma to Full Product',
    subtitle: 'Master Figma, design systems, user research, prototyping, and handoff',
    description: 'Learn the complete product design workflow. From user research and wireframing to high-fidelity designs and developer handoff. Master Figma, build design systems, create interactive prototypes, conduct usability testing, and learn the design thinking process used at top tech companies.',
    price: 11.99,
    originalPrice: 69.99,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    instructor: {
      name: 'Maya Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80',
      title: 'Design Director at Spotify',
      bio: 'Led design for products used by 500M+ people. Former Apple Design team.',
    },
    category: 'UI/UX Design',
    level: 'Beginner',
    rating: 4.8,
    totalRatings: 9876,
    studentsEnrolled: 45230,
    totalDuration: '36h 50m',
    totalLessons: 245,
    tags: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
    isBestseller: true,
    lessons: [
      { title: 'What Makes Great Design?', duration: '12:00', isPreview: true },
      { title: 'Figma Interface & Setup', duration: '18:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Jordan Lee', rating: 5, comment: 'Career-changing course. Landed my first UX role thanks to the portfolio projects.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345607',
    title: 'Full-Stack Node.js — Microservices with Docker & Kubernetes',
    subtitle: 'Build scalable backends with Node.js, Docker, K8s, and CI/CD pipelines',
    description: 'Master backend engineering at scale. Learn to build microservices architecture with Node.js, containerize with Docker, orchestrate with Kubernetes, set up CI/CD pipelines with GitHub Actions, implement message queues with RabbitMQ, and monitor with Prometheus and Grafana.',
    price: 18.99,
    originalPrice: 119.99,
    thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&q=80',
    instructor: {
      name: 'Erik Lindgren',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
      title: 'Staff Engineer at Shopify',
      bio: 'Built systems handling 1M+ requests per second. Open source contributor.',
    },
    category: 'DevOps',
    level: 'Advanced',
    rating: 4.6,
    totalRatings: 5432,
    studentsEnrolled: 21890,
    totalDuration: '40h 5m',
    totalLessons: 268,
    tags: ['Node.js', 'Docker', 'Kubernetes', 'Microservices', 'DevOps', 'CI/CD'],
    isBestseller: false,
    lessons: [
      { title: 'Monolith vs Microservices', duration: '16:00', isPreview: true },
      { title: 'Node.js at Scale — Best Practices', duration: '24:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Chris Park', rating: 5, comment: 'This course completely changed how I think about backend architecture.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345608',
    title: 'Ethical Hacking & Cybersecurity Bootcamp',
    subtitle: 'Learn penetration testing, network security, and bug bounty hunting',
    description: 'Become a cybersecurity professional. Learn ethical hacking, penetration testing, network security, web application security, social engineering, and cryptography. Covers tools like Kali Linux, Burp Suite, Metasploit, Wireshark, and Nmap. Prepare for the CEH certification.',
    price: 15.99,
    originalPrice: 99.99,
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    instructor: {
      name: 'Daniel Osei',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80',
      title: 'Chief Security Officer at CrowdStrike',
      bio: 'Former NSA cybersecurity analyst. Found vulnerabilities in Fortune 500 systems.',
    },
    category: 'Cybersecurity',
    level: 'Beginner',
    rating: 4.8,
    totalRatings: 11234,
    studentsEnrolled: 56780,
    totalDuration: '46h 30m',
    totalLessons: 298,
    tags: ['Cybersecurity', 'Ethical Hacking', 'Penetration Testing', 'Kali Linux', 'Bug Bounty'],
    isBestseller: false,
    lessons: [
      { title: 'Introduction to Cybersecurity', duration: '14:00', isPreview: true },
      { title: 'Setting Up Your Hacking Lab', duration: '20:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Kevin Wu', rating: 5, comment: 'Earned my first bug bounty reward ($2,500) after taking this course!' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345609',
    title: 'Flutter & Dart — Cross-Platform App Development',
    subtitle: 'Build beautiful iOS & Android apps with a single codebase',
    description: 'Master Flutter and Dart to build stunning cross-platform mobile applications. Covers widget trees, state management with Riverpod, Firebase integration, REST APIs, local storage, animations, and publishing to both App Store and Google Play. Build 8 complete apps.',
    price: 13.99,
    originalPrice: 84.99,
    thumbnail: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
    instructor: {
      name: 'Leila Ahmadi',
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&q=80',
      title: 'Mobile Tech Lead at Google',
      bio: 'Core contributor to Flutter framework. Speaker at Google I/O.',
    },
    category: 'Mobile Development',
    level: 'Beginner',
    rating: 4.7,
    totalRatings: 7654,
    studentsEnrolled: 38920,
    totalDuration: '35h 40m',
    totalLessons: 224,
    tags: ['Flutter', 'Dart', 'Mobile', 'Cross-Platform', 'Firebase'],
    isBestseller: false,
    lessons: [
      { title: 'Why Flutter? — The Cross-Platform Future', duration: '10:00', isPreview: true },
      { title: 'Dart Language Crash Course', duration: '28:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Marco Rossi', rating: 5, comment: 'Published my first app on both stores in just 3 months of learning!' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345610',
    title: 'Advanced TypeScript — Design Patterns & Architecture',
    subtitle: 'Master generics, type gymnastics, and scalable TypeScript codebases',
    description: 'Go beyond the basics of TypeScript. This advanced course covers complex generics, conditional types, mapped types, template literal types, design patterns (Factory, Observer, Strategy, Decorator), clean architecture, and building type-safe libraries. Essential for senior developers.',
    price: 17.99,
    originalPrice: 99.99,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
    instructor: {
      name: 'Henrik Müller',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&q=80',
      title: 'TypeScript Core Team Contributor',
      bio: 'Author of "TypeScript in Depth." Microsoft MVP for 5 consecutive years.',
    },
    category: 'Web Development',
    level: 'Advanced',
    rating: 4.9,
    totalRatings: 4321,
    studentsEnrolled: 18760,
    totalDuration: '28h 15m',
    totalLessons: 186,
    tags: ['TypeScript', 'Design Patterns', 'Architecture', 'JavaScript', 'Advanced'],
    isBestseller: false,
    lessons: [
      { title: 'TypeScript Compiler Deep Dive', duration: '22:00', isPreview: true },
      { title: 'Advanced Generics — Beyond the Basics', duration: '30:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Laura Schmidt', rating: 5, comment: 'Finally understand advanced TS patterns. This filled so many knowledge gaps.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345611',
    title: 'Blockchain Development with Solidity & Web3',
    subtitle: 'Build decentralized apps, smart contracts, and DeFi protocols',
    description: 'Enter the world of blockchain development. Learn Solidity, smart contract development, testing with Hardhat, frontend integration with ethers.js, ERC-20 & ERC-721 token standards, DeFi protocols, and deploying to Ethereum and Polygon networks. Build 6 complete dApps.',
    price: 21.99,
    originalPrice: 129.99,
    thumbnail: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
    instructor: {
      name: 'Satoshi Yamamoto',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&q=80',
      title: 'Blockchain Lead at Coinbase',
      bio: 'Built DeFi protocols with $500M+ TVL. Ethereum Foundation grantee.',
    },
    category: 'Web Development',
    level: 'Intermediate',
    rating: 4.6,
    totalRatings: 3456,
    studentsEnrolled: 15670,
    totalDuration: '32h 20m',
    totalLessons: 210,
    tags: ['Blockchain', 'Solidity', 'Web3', 'Ethereum', 'DeFi', 'Smart Contracts'],
    isBestseller: false,
    lessons: [
      { title: 'Blockchain Fundamentals', duration: '18:00', isPreview: true },
      { title: 'Solidity — Your First Smart Contract', duration: '24:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Alex Chen', rating: 5, comment: 'The DeFi section alone is worth the price. Incredible depth.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345612',
    title: 'Complete SQL & Database Engineering',
    subtitle: 'Master PostgreSQL, query optimization, indexing, and database design',
    description: 'Become a database expert. This course covers SQL from basics to advanced, PostgreSQL administration, query optimization, indexing strategies, database design and normalization, transactions and concurrency, replication, and partitioning. Includes real-world performance tuning scenarios.',
    price: 9.99,
    originalPrice: 59.99,
    thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    instructor: {
      name: 'Olga Petrov',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&q=80',
      title: 'Principal Database Engineer at Uber',
      bio: 'Managed databases serving 20M+ queries per day. PostgreSQL committer.',
    },
    category: 'Data Science',
    level: 'Beginner',
    rating: 4.7,
    totalRatings: 8901,
    studentsEnrolled: 42350,
    totalDuration: '30h 45m',
    totalLessons: 198,
    tags: ['SQL', 'PostgreSQL', 'Database', 'Backend', 'Data Engineering'],
    isBestseller: false,
    lessons: [
      { title: 'SQL Fundamentals — SELECT, WHERE, JOIN', duration: '25:00', isPreview: true },
      { title: 'Advanced Queries — Subqueries & CTEs', duration: '30:30', isPreview: true },
    ],
    reviews: [
      { userName: 'Paul Anderson', rating: 5, comment: 'Best SQL course on the internet. The optimization section saved my job.' },
    ],
  },
  {
    _id: '658c1f107f9c8f0012345678',
    title: 'Web Development 101 (webdev101)',
    subtitle: 'Learn HTML, CSS, JavaScript, and build your first website',
    description: 'The ultimate beginner course for web development. Learn how the web works, write clean HTML5 and CSS3, understand layout systems like Flexbox and Grid, and add interactivity using modern JavaScript. You will build and deploy a responsive personal portfolio site.',
    price: 9.99,
    originalPrice: 49.99,
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    instructor: {
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
      title: 'Senior Frontend Engineer at Meta',
      bio: 'Enthusiastic educator with 10+ years of frontend experience.'
    },
    category: 'Web Development',
    level: 'Beginner',
    rating: 4.9,
    totalRatings: 420,
    studentsEnrolled: 3500,
    totalDuration: '12h 15m',
    totalLessons: 55,
    tags: ['HTML', 'CSS', 'JavaScript', 'Web Dev', 'Beginner'],
    isBestseller: true,
    lessons: [
      { title: 'Welcome & Course Overview', duration: '4:15', isPreview: true },
      { title: 'How the Web Works', duration: '8:30', isPreview: true },
      { title: 'HTML Basics — Tags & Structure', duration: '15:45', isPreview: false },
      { title: 'CSS Styling & the Box Model', duration: '22:10', isPreview: false },
    ],
    reviews: [
      { userName: 'John Doe', rating: 5, comment: 'Absolutely amazing for complete beginners. Easy to follow!' }
    ]
  },
  {
    _id: '658c1f107f9c8f0012345679',
    title: 'AI/ML 101 (ai/ml 101)',
    subtitle: 'Learn the fundamentals of Machine Learning, Python, and TensorFlow',
    description: 'An introductory course to Artificial Intelligence and Machine Learning. Get a quick start on Python basics, learn supervised vs unsupervised learning, understand linear & logistic regression, and build your very first neural network with TensorFlow. Perfect for beginners who want to break into AI.',
    price: 12.99,
    originalPrice: 79.99,
    thumbnail: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=800&q=80',
    instructor: {
      name: 'Dr. James Okonkwo',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
      title: 'Lead Data Scientist at Netflix',
      bio: 'PhD in Machine Learning from Stanford. Passionate about AI education.'
    },
    category: 'AI & Machine Learning',
    level: 'Beginner',
    rating: 4.8,
    totalRatings: 310,
    studentsEnrolled: 2800,
    totalDuration: '15h 45m',
    totalLessons: 68,
    tags: ['AI', 'Machine Learning', 'Python', 'TensorFlow', 'Data Science'],
    isBestseller: true,
    lessons: [
      { title: 'Introduction to AI & Machine Learning', duration: '6:20', isPreview: true },
      { title: 'Python Crash Course for AI', duration: '20:45', isPreview: true },
    ],
    reviews: [
      { userName: 'Mark Taylor', rating: 5, comment: 'Clear, intuitive explanations. The python intro was very helpful!' }
    ]
  }
];

export const MOCK_CATEGORIES = [
  'Web Development',
  'Mobile Development',
  'Data Science',
  'AI & Machine Learning',
  'Cloud Computing',
  'UI/UX Design',
  'Cybersecurity',
  'DevOps'
];
